// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: players/players.proto

package exhibit_backend

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReq) Reset() {
	*x = PlayerReq{}
	mi := &file_players_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReq) ProtoMessage() {}

func (x *PlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_players_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReq.ProtoReflect.Descriptor instead.
func (*PlayerReq) Descriptor() ([]byte, []int) {
	return file_players_players_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResp) Reset() {
	*x = PlayerResp{}
	mi := &file_players_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResp) ProtoMessage() {}

func (x *PlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_players_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResp.ProtoReflect.Descriptor instead.
func (*PlayerResp) Descriptor() ([]byte, []int) {
	return file_players_players_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_players_players_proto protoreflect.FileDescriptor

const file_players_players_proto_rawDesc = "" +
	"\n" +
	"\x15players/players.proto\x12\aplayers\x1a\x1cgoogle/api/annotations.proto\"\x1f\n" +
	"\tPlayerReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\n" +
	"PlayerResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2_\n" +
	"\rPlayerService\x12N\n" +
	"\tGetPlayer\x12\x12.players.PlayerReq\x1a\x13.players.PlayerResp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/getPlayerB#Z!github.com/timrxd/exhibit-backendb\x06proto3"

var (
	file_players_players_proto_rawDescOnce sync.Once
	file_players_players_proto_rawDescData []byte
)

func file_players_players_proto_rawDescGZIP() []byte {
	file_players_players_proto_rawDescOnce.Do(func() {
		file_players_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_players_players_proto_rawDesc), len(file_players_players_proto_rawDesc)))
	})
	return file_players_players_proto_rawDescData
}

var file_players_players_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_players_players_proto_goTypes = []any{
	(*PlayerReq)(nil),  // 0: players.PlayerReq
	(*PlayerResp)(nil), // 1: players.PlayerResp
}
var file_players_players_proto_depIdxs = []int32{
	0, // 0: players.PlayerService.GetPlayer:input_type -> players.PlayerReq
	1, // 1: players.PlayerService.GetPlayer:output_type -> players.PlayerResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_players_players_proto_init() }
func file_players_players_proto_init() {
	if File_players_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_players_players_proto_rawDesc), len(file_players_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_players_players_proto_goTypes,
		DependencyIndexes: file_players_players_proto_depIdxs,
		MessageInfos:      file_players_players_proto_msgTypes,
	}.Build()
	File_players_players_proto = out.File
	file_players_players_proto_goTypes = nil
	file_players_players_proto_depIdxs = nil
}
